service: testconverter
frameworkVersion: '2'

provider:
  name: aws
  region: eu-central-1
  memorySize: 1024
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - ${self:custom.connectionParams.ResultNotificationQueueArn}
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - { "Fn::Join" : [ "", [ "arn:aws:s3:::", "${self:custom.connectionParams.OriginalBucketName}", "/*"] ]}
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - { "Fn::Join" : [ "", [ "arn:aws:s3:::", "${self:custom.connectionParams.ResultBucketName}", "/*"] ]}

functions:
  Converter:
    image: ${self:custom.extra.Image}
    timeout: 600
    environment:
      CONVERTER_NAME: ${self:custom.extra.Name}
      RESULT_NOTIFICATION_QUEUE: ${self:custom.connectionParams.ResultNotificationQueueEndpoint}
      RESULT_BUCKET_NAME: ${self:custom.connectionParams.ResultBucketName}
    events:
     - sqs:
         arn: !GetAtt ConvertFileQueue.Arn

custom:
  stage: ${opt:stage, self:provider.stage}
  extra: ${file(vars/${self:custom.stage}.yml)}
  connectionParams: ${file(connection_params.yml)}

resources:
  Resources:
    ConvertFileQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        VisibilityTimeout: 1200

    ConvertFileQueuePolicy:
      Type: "AWS::SQS::QueuePolicy"
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: Allow-SNS-SendMessage
            Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource: !GetAtt ConvertFileQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: ${self:custom.connectionParams.FileUploadedTopic}
        Queues:
          - !Ref ConvertFileQueue

    ConvertFileQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt ConvertFileQueue.Arn
        Region: "${self:provider.region}"
        TopicArn: ${self:custom.connectionParams.FileUploadedTopic}
        RawMessageDelivery: 'true'
