service: testconvertersapp

frameworkVersion: '2'

# npm install serverless-s3-remover
plugins:
  - serverless-s3-remover

provider:
  name: aws
  region: eu-central-1
  runtime: dotnetcore3.1
  memorySize: 128
  lambdaHashingVersion: 20201221
  
package:
  individually: true

custom:
  remover:
     buckets:
        - { Ref: InputBucket }


iamRoleStatements:
    - Effect: Allow
      Action:
      - sns:Publish
      Resource:
        - !GetAtt FileUploadedTopic.Arn

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    environment:
      FANOUT_TOPIC_ARN: { Ref: FileUploadedTopic }
    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip
    events:
      - s3:
          bucket:  { Ref: InputBucket }
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    InputBucket:
      Type: "AWS::S3::Bucket"

    FileUploadedTopic:
      Type: "AWS::SNS::Topic"

    DummyConverterQueue:
      Type: "AWS::SQS::Queue"

    DummyQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: { "Fn::GetAtt": ["DummyConverterQueue", "Arn"] }
        TopicArn: { Ref: FileUploadedTopic }
