service: testconvertersapp

frameworkVersion: '2'

provider:
  name: aws
  region: eu-central-1
  runtime: dotnetcore3.1
  memorySize: 128
  lambdaHashingVersion: 20201221
  
package:
  individually: true

functions:
  hello:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip
    events:
      - s3:
          bucket:  { Ref: InputBucket }
          existing: true

resources:
  Resources:
    InputBucket:
      Type: "AWS::S3::Bucket"

    FileUploadedTopic:
      Type: "AWS::SNS::Topic"